name: Build Windows Executable

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13.2"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller
                  if (Test-Path requirements.txt) { pip install -r requirements.txt }

            - name: Build with PyInstaller
              run: |
                  pyinstaller --clean -F -w -n DriveConversor main.py --icon=macos/icon.png

            - name: Get version from date
              id: version
              shell: pwsh
              run: |
                  $date = Get-Date -Format "yyyyMMddHHmmss"
                  echo "tag=v$date" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.version.outputs.tag }}
                  release_name: Release ${{ steps.version.outputs.tag }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: "dist/DriveConversor.exe"
                  asset_name: DriveConversor-windows.exe
                  asset_content_type: application/octet-stream
