name: Build macOS Executable

on:
    push:
        branches: [main]
    workflow_dispatch:
permissions:
    contents: write
jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13.2"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Instalar Pillow para generar icono
              run: pip install pillow

            - name: Generar icono cuadrado negro
              run: python macos/generate_icon.py

            - name: Convertir icono PNG a ICNS
              run: |
                  mkdir -p macos/icon.iconset
                  sips -z 512 512 macos/icon.png --out macos/icon.iconset/icon_512x512.png
                  iconutil -c icns macos/icon.iconset -o macos/icon.icns

            - name: Build bundle .app con PyInstaller
              run: |
                  pyinstaller --clean --windowed --name "DriveConversor" main.py \
                  --icon=macos/icon.icns \
                  --osx-bundle-identifier com.tuempresa.drivelinkconversor

            - name: Comprimir el bundle .app
              run: |
                  cd dist
                  zip -r DriveConversor-macos-app.zip DriveConversor.app
                  cd ..

            - name: Get version from date
              id: version
              run: echo "::set-output name=tag::v$(date +'%Y%m%d%H%M%S')"

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.version.outputs.tag }}
                  release_name: Release ${{ steps.version.outputs.tag }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: "dist/DriveConversor-macos-app.zip"
                  asset_name: DriveConversor-macos-app.zip
                  asset_content_type: application/zip
